# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    open-pull-requests-limit: 100
    assignees:
      - 'jsamuelsen'
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: '⬆️'
      include: 'scope'
    versioning-strategy: 'increase'
    groups:
      # Group security updates for faster merging
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'
      # Group React ecosystem updates
      react:
        patterns:
          - 'react*'
          - '@types/react*'
      # Group Next.js updates
      nextjs:
        patterns:
          - 'next'
          - '@next/*'
      # Group testing dependencies
      testing:
        patterns:
          - 'jest*'
          - '@testing-library/*'
          - 'playwright'
          - '@playwright/*'
      # Group linting and formatting
      code-quality:
        patterns:
          - 'eslint*'
          - 'prettier'
          - '@typescript-eslint/*'
          - 'stylelint*'

  # Docker base image updates
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '06:00'
    assignees:
      - 'jsamuelsen'
    labels:
      - 'docker'
      - 'security'
    commit-message:
      prefix: '🐳'
      include: 'scope'

  # GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '06:00'
    assignees:
      - 'jsamuelsen'
    labels:
      - 'github-actions'
      - 'ci-cd'
    commit-message:
      prefix: '🔧'
      include: 'scope'
