name: 🐛 Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched the existing issues to make sure this bug hasn't been reported yet
          required: true
        - label: I am using the latest version of the Recipe UI Service
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide the exact steps to reproduce this bug
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment is this happening in?
      options:
        - Development (npm run dev)
        - Production (deployed)
        - Testing
        - Staging
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: |
        Please provide system information
        (You can get this by running `npm run --version` and `node --version`)
      placeholder: |
        - OS: [e.g. macOS 13.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g. 20.10.0]
        - npm version: [e.g. 10.2.3]
        - Browser version: [e.g. Chrome 118.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Screenshots
      description: |
        Please paste any relevant console errors or attach screenshots.
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
      placeholder: |
        Paste console errors here or drag and drop screenshots

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Critical functionality broken
        - Urgent - Production system down
    validations:
      required: true
