blank_issues_enabled: false
contact_links:
  - name: 🔒 Critical Security Vulnerability
    url: mailto:jsamuelsen11@gmail.com
    about: For critical security issues, please email us directly instead of creating a public issue
  - name: 💬 General Discussion
    url: https://github.com/jsamuelsen/recipe-web-app/discussions
    about: For general questions, ideas, and community discussions
  - name: 📖 Documentation
    url: https://github.com/jsamuelsen/recipe-web-app/tree/main/recipe-ui-service
    about: Check our comprehensive documentation and guides
  - name: 🚀 Feature Roadmap
    url: https://github.com/jsamuelsen/recipe-web-app/projects
    about: View our roadmap and planned features
