---
name: Security Vulnerability
description: Report a security vulnerability (for low-severity issues only)
title: '[Security]: '
labels: ['security', 'needs-triage']
assignees:
  - jsamuelsen
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT SECURITY NOTICE ⚠️

        **For CRITICAL or HIGH severity security vulnerabilities, please DO NOT create a public issue.**

        Instead, please use GitHub Security Advisories:
        👉 [Report a Security Vulnerability](https://github.com/Recipe-Web-App/recipe-ui-service/security/advisories/new)

        **Only use this template for LOW severity security issues or security enhancements.**

  - type: checkboxes
    id: terms
    attributes:
      label: Security Disclosure Agreement
      description: By submitting this issue, you agree to responsible disclosure practices
      options:
        - label: This is NOT a critical or high severity vulnerability
          required: true
        - label: I have read and agree to follow responsible disclosure practices
          required: true
        - label: I have searched existing issues to ensure this hasn't been reported yet
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: What is the severity of this security issue?
      options:
        - Low - Limited impact, specific conditions required
        - Informational - Security enhancement or best practice
    validations:
      required: true

  - type: dropdown
    id: security-category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Dependency Vulnerability
        - Configuration Security
        - Authentication/Authorization
        - Data Validation
        - Information Disclosure (limited)
        - Security Headers
        - CORS Configuration
        - XSS (Limited Impact)
        - CSRF Protection
        - Security Enhancement
        - Security Documentation
        - Privacy Concern
        - Compliance Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Clearly describe the security concern
      placeholder: |
        - What is the security issue?
        - Why is this a concern?
        - What could happen if exploited?
        - Why is this low severity?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact if this issue is exploited?
      placeholder: |
        - Who is affected?
        - What data/functionality is at risk?
        - What are the prerequisites for exploitation?
        - Why is the impact limited?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this security issue be reproduced?
      placeholder: |
        1. Go to '...'
        2. Do '...'
        3. Observe security issue
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the application are affected?
      placeholder: |
        - Specific files, routes, or components
        - Configuration files
        - Dependencies
        - Frontend/Backend areas

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Do you have suggestions for how to fix this?
      placeholder: |
        - Recommended security controls
        - Configuration changes
        - Code improvements
        - Dependency updates

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: In what environment did you discover this?
      placeholder: |
        - Browser/Version:
        - OS:
        - Node.js version:
        - Deployment environment:

  - type: textarea
    id: references
    attributes:
      label: Security References
      description: Any relevant security documentation?
      placeholder: |
        - CVE IDs (if applicable)
        - OWASP references
        - Security best practices
        - Related security issues

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure
      description: Confirm your commitment to responsible disclosure
      options:
        - label: I will not publicly disclose details until a fix is available
          required: true
        - label: I have not shared this vulnerability publicly
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
