name: 🔒 Security Issue
description: Report a security vulnerability (for non-critical issues only)
title: '[Security]: '
labels: ['security', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT SECURITY NOTICE ⚠️

        **For critical security vulnerabilities, please DO NOT create a public issue.**

        Instead, please follow our responsible disclosure process:
        1. Email security details to: [jsamuelsen11@gmail.com](mailto:jsamuelsen11@gmail.com)
        2. Include "SECURITY" in the subject line
        3. We will respond within 24 hours
        4. Please allow us time to fix the issue before public disclosure

        **Only use this template for low-risk security improvements or non-sensitive security discussions.**

  - type: checkboxes
    id: terms
    attributes:
      label: Security Disclosure Agreement
      description: By submitting this issue, you agree to responsible disclosure practices
      options:
        - label: This is NOT a critical security vulnerability that could be exploited
          required: true
        - label: I have read and agree to follow responsible disclosure practices
          required: true
        - label: I have searched existing issues to ensure this hasn't been reported yet
          required: true

  - type: dropdown
    id: security-type
    attributes:
      label: Security Issue Type
      description: What type of security issue is this?
      options:
        - Security enhancement suggestion
        - Dependency vulnerability (non-critical)
        - Configuration security improvement
        - Documentation security update
        - Security testing improvement
        - Privacy concern
        - GDPR/compliance question
        - Security audit suggestion
        - Other non-critical security topic
    validations:
      required: true

  - type: textarea
    id: security-description
    attributes:
      label: Security Issue Description
      description: Describe the security concern or improvement suggestion
      placeholder: |
        Please provide:
        - Clear description of the security concern
        - Why this is a security issue
        - What could be improved
        - Potential impact (should be low-risk for public discussion)
    validations:
      required: true

  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Level Assessment
      description: What's your assessment of the risk level?
      options:
        - Informational - General security improvement suggestion
        - Low - Minor security enhancement with minimal impact
        - Medium - Security improvement with moderate impact
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the application are affected?
      placeholder: |
        - Specific files, functions, or features
        - Dependencies or configurations
        - User-facing components
        - Admin/backend systems

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: How does the system currently behave?
      placeholder: Describe the current implementation or behavior that could be improved from a security perspective

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Security Improvement
      description: What would you recommend to improve security?
      placeholder: |
        - Specific changes or configurations
        - Best practices that could be implemented
        - Tools or processes that could be added
        - References to security standards or guidelines

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any technical details about how this could be implemented?
      placeholder: |
        - Code changes needed
        - Configuration updates
        - Testing considerations
        - Compatibility concerns

  - type: textarea
    id: references
    attributes:
      label: Security References
      description: Any relevant security documentation or standards?
      placeholder: |
        - OWASP guidelines
        - Security best practices articles
        - CVE references (if applicable)
        - Industry standards

  - type: checkboxes
    id: testing-willingness
    attributes:
      label: Testing and Implementation
      description: Can you help with this security improvement?
      options:
        - label: I can help test the security improvement
        - label: I can help implement the security improvement
        - label: I can provide additional security expertise
        - label: I can help with security documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about this security issue?
