name: Greet Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greet:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time issue creators
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.issue.user.login;

            // Check if this is the first issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: creator,
              state: 'all'
            });

            if (issues.data.length === 1) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: `👋 **Welcome to Recipe UI Service, @${creator}!**

            Thank you for creating your first issue! We appreciate your contribution to the project.

            **What happens next?**
            - A maintainer will review your issue and may ask for additional information
            - We aim to respond within 48 hours
            - Feel free to join the discussion and provide any additional context

            **Helpful Resources:**
            - [Contributing Guide](.github/CONTRIBUTING.md)
            - [Code of Conduct](.github/CODE_OF_CONDUCT.md)
            - [Support Documentation](.github/SUPPORT.md)

            We're excited to have you in our community! 🎉`
              });
            }

      - name: Greet first-time PR creators
        if: github.event_name == 'pull_request_target'
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.pull_request.user.login;

            // Check if this is the first PR
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all'
            });

            const userPRs = prs.data.filter(pr => pr.user.login === creator);

            if (userPRs.length === 1) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `👋 **Welcome, @${creator}!**

            Thank you for opening your first pull request! We're thrilled to have you contribute to Recipe UI Service.

            **Review Process:**
            - A maintainer will review your PR soon
            - We may request changes or provide feedback
            - Please make sure all CI checks pass
            - Feel free to ask questions if you need help

            **Before Merging:**
            - [ ] All tests pass
            - [ ] Code follows project style guidelines
            - [ ] Documentation is updated (if needed)
            - [ ] No merge conflicts

            **Helpful Resources:**
            - [Contributing Guide](.github/CONTRIBUTING.md)
            - [Development Guide](CLAUDE.md)
            - [Pull Request Template](.github/PULL_REQUEST_TEMPLATE.md)

            Thank you for your contribution! 🚀`
              });
            }
